version: '3'
services:
  app:
    container_name: "app"
    build:
      context: ./
      dockerfile: app.dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    links:
      - database
    environment:
      DB_HOST: database
      DB_DATABASE: homestead
      DB_USERNAME: root
      DB_PASSWORD: secret
  web:
    container_name: "web"
    build:
      context: ./
      dockerfile: web.dockerfile
    links:
      - app
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
  database:
    container_name: "database"
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
